sudo: required
services:
  - docker
before_install:
  - gem install bundler
  - docker build -t miguelgmedina/docker-react -f Dockerfile.dev .
script:
  - docker run miguelgmedina/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-743401033072"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"