sudo: required
services:
  - docker
before_install:
  - gem install bundler
  - docker build -t miguelgmedina/docker-react -f Dockerfile.dev .
script:
  - docker run miguelgmedina/docker-react npm run test -- --coverage
  
#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master